directory_name: patch_uniform
generator_image_parameters:
  channels: 1
  side: 40
generator_images: gen_patch_uniform
generator_noise: gen_noise_uniform
generator_noise_parameters:
  max_val: 0.005
  min_val: 0.0001
location: /mnt/nvme_1/stage/victor/Data
n_samples: 50000
shading:
  parameters:
    elevation: 1
    x_range:
      max: 1.2
      min: -0.2
    y_range:
      max: 1.2
      min: -0.2
  status: true
train_split: 0.8
