location: "/mnt/nvme_1/stage/victor/Data"
directory_name: patch_uniform
shading:
  status: True
  parameters:
    elevation: 1
    x_range:
      min: -0.2
      max: 1.2
    y_range:
      min: -0.2
      max: 1.2
generator_image_parameters:
  channels: 1
  side: 40
generator_images: gen_patch_uniform 
generator_noise: gen_noise_uniform
generator_noise_parameters:
  max_val: 0.005
  min_val: 0.0001
n_samples: 50000
train_split: 0.8
