generators_noise_config:
  - uniform:
    generator_noise_parameters:
      max_val: 0.005
      min_val: 0.0001
    generator_noise: gen_noise_uniform

  - beta:
    generator_noise_parameters:
      alpha: 1
      beta: 1
      max_val: 0.005
      min_val: 0.0001
    generator_noise: gen_noise_uniform
