directory_name: patch_uniform
generator_image_parameters:
  channels: 1
  side: 40
generator_images: gen_patch_uniform
generator_noise: gen_noise_uniform
generator_noise_parameters:
  max_val: 0.005
  min_val: 0.0001
location: /home/victor-scht/Documents/Innov+/Data/
n_samples: 1000
shading:
  parameters:
    elevation: 3
    x_range:
      max: 1.2
      min: -0.2
    y_range:
      max: 1.2
      min: -0.2
  status: true
train_split: 0.8
